name: CI/CD for Dockerized FastAPI App

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub (if using Docker Hub)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:latest .
          docker push ${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Fetch latest changes
          run: git fetch --all

        - name: Initialize submodules
          run: git submodule update --init --recursive

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

          
        - name: EC2 Docker Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_IP }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.PEM }}
            script: |
              cd git-action-test/
              sed -i 's|image:.*|image: '"${{ secrets.DOCKER_IMAGE }}:latest"'|' docker-compose.yml
              docker-compose down
              docker-compose pull
              docker-compose up -d
